function trans_matrix = compute_trans_matrix(theta_deg)
c = cosd(theta_deg);
s = sind(theta_deg);
trans_matrix = [c^2, s*c, -c^2, -s*c;...
                s*c, s^2, -s*c, -s^2;...
                -c^2, -s*c, c^2, s*c;...
                -s*c, -s^2, s*c, s^2];
end